name: flutter_cached_pdfview
description: A package to show a Native PDF View for iOS and Android, supports opening and caching from different resources like Path, Asset, and Url.
version: 0.5.0
homepage: https://base1.com
repository: https://github.com/BASE1com/flutter_cached_pdfview
issue_tracker: https://github.com/BASE1com/flutter_cached_pdfview/issues
environment:
  sdk: ">=2.12.0 <4.0.0"
# new pubspec
#https://flutter.dev/docs/development/packages-and-plugins/developing-packages
dependencies:
  flutter:
    sdk: flutter
  flutter_pdfview: ">=1.2.0 <2.0.0"
  flutter_cache_manager: ">=3.0.0 <4.0.0"
  path_provider: ">=2.0.0 <3.0.0"
  path: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
